FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist/resume-website/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
